[project]
name = "stems-demucs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "audioread>=3.0.1",
    "demucs>=4.0.1",
    "librosa>=0.11.0",
    "soundfile>=0.13.1",
    "torch>=2.8.0",
    "torchaudio>=2.8.0",
]
